### PR TITLE
feat: stop creating `mbta_uuid` for new users

### PR DESCRIPTION
**Pull request by paulswartz**
@jurakp I don't see any tests or build steps in the repo; how do you all test changes here?

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1207566363685657

### CODE REVIEW

**Comment by integsoft-company** [comment]
@paulswartz, we need to bring in another reviewer who has made some updates to the code for the new Keycloak version planned for sandbox release.

**Comment by paulswartz** [comment]
@jurakp sure thing! Or feel free to drop this change into the existing development.

**Comment by jurakp** [comment]
@paulswartz We need to add `tomaskozany` (which is Tomas Kozany's GH account) as a reviewer. Could you please do it? You may need to add him as a team member in the MBTA space.  
Anyway for me the PR looks good.  So once Tomas Kozany also approves, we can merge it. The we can process it on our side with the other ongoing changes to the sandbox environment.

**Comment by paulswartz** [comment]
@jurakp I invited @tomaskozany to the repository. Once they accept the invite, they should be able to add themselves as a reviewer.

**Pull request merged**
